name: deploy-to-heroku

on:
  push:
    branches: ["main"]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt --upgrade pip
        pip install pylint
    - name: Lint Python Code
      run: pylint $(git ls-files '*.py')

  deploy-app:
    needs: [python-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy App to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "brawlstars-clubleague-tracker" #Must be unique in Heroku
          heroku_email: "${{ github.event.pusher.email }}"